version: 1.0.{build}
environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      HOST: x86_64-pc-windows-gnu
      TARGET: x86_64-pc-windows-gnu
      BIN_NAME: pngquant
      ARCHIVE_NAME: pngquant-windows-x86_64
      MODE: release
for:
  -
    matrix:
      only:
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
          TARGET: x86_64-pc-windows-gnu
    install:
      - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
      - rustup-init -yv --default-toolchain stable --default-host %HOST%
      - set PATH=%PATH%;%USERPROFILE%\.cargo\bin
      - rustc -V
      - cargo -V
      - set PATH=%PATH%;C:\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1\mingw64\bin
      - g++ --version
    build_script:
      - if "%MODE%" == "release" ( set RELEASE_FLAG=--release& set TARGET_DIR=release& set NAME_SUFFIX=) else ( set RELEASE_FLAG=& set TARGET_DIR=debug& set NAME_SUFFIX=-debug)
      - set FULL_NAME=%ARCHIVE_NAME%%NAME_SUFFIX%-%APPVEYOR_REPO_BRANCH%
      - mkdir tmp
      - cd tmp
      - git clone -b msvc --recursive https://github.com/kornelski/pngquant.git
      - cd pngquant
      - cargo build --release
    after_build:
      - 7z a %APPVEYOR_BUILD_FOLDER%/all.zip %APPVEYOR_BUILD_FOLDER%
    artifacts:
      - path: all.zip
        name: all
